version: "2"
services:
    nginx:
        image: nginx:1.12.1-alpine
        ports:
            - "80:80"
        volumes_from:
            - php5.6
        volumes:
            - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/nginx/vhost:/etc/nginx/conf.d
    php5.6:
        image: php:5.6-fpm-alpine
        volumes:
            - ./wwwroot:/home/wwwroot
    php7.2:
        image: php:7.2-rc-fpm-alpine
        volumes:
            - ./wwwroot:/home/wwwroot
    mysql5.6:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test123"
